ansible-community/awesome-ansible

README.md
Hard to give a good objective reason since it's my own blog post. The article is very popular since it came out, and tries to cover many aspects of a maintainable, understandable Ansible setup including explanations of distinguishing environments (testing, staging, production) nicely.
=> Add best practices article

README.md
https://hackr.io/tutorials/learn-ansible
=> Added Curated Ansible Resources

.travis.yml, README.md
- Clean up dead and redirected links.
- Make Travis CI Pass again
=> update rub rvm to version 2.6

README.md
Adds `Ansible for Kubernetes` and improves the Description of `Ansible for Devops`
=> adds Ansible for Kubernetes

README.md
Adds the Great Video Series on Ansible by Jeff Geerling!
=> adds Ansible 101 by Jeff Geerling

README.md
https://github.com/sindresorhus/awesome/pull/1857#issuecomment-687655299
Apply improvements suggested by @keller-mark
=> style(readme): adds description to video section, fixes typo

README.md
https://github.com/sindresorhus/awesome/pull/1857#issuecomment-701402574
=> style: adhere to official awesome list style requirements

README.md
Hi o/
I'm the author of ara and I had originally added it to another awesome-ansible list: https://github.com/jdauphant/awesome-ansible/commit/d11e73e8e3aa187f6c8655ce0b06e32e670477d0
It seems this is the new place now ? Thanks for maintaining it :+1:
=> Update listing for ara

README.md
Add Ansible SSM (https://github.com/HQarroum/ansible-ssm).
=> Add ansible-ssm

.gitignore, CONTRIBUTING.md, README.md
=> Addtions to Tools

README.md
Added YouTube video tutorial series by LearnLinuxTV.
=> Update README.md to include LearnLinuxTV tutorial

README.md
Dear maintainers,
This is a proposal to include BlueBanquise project resources into your awesome list 😊
=> Doc: README.md - Include BlueBanquise

README.md
ansible-toolset doesn't seem to exist anymore, so I'm removing it from the awesome tools list.
=> Remove ansible-toolset

README.md
I was asked to add single blog posts instead of a category URL to my blog. I did so in this PR.
=> Three articles instead of blog category

README.md
Hello,
Add link Ansible Semaphore Tool.
Thanks
=> Add Ansible Semaphore tool

README.md
Add Robert de Bock Role collection
=> Add Robert de Bock Roles

README.md
This PR adds a link to [Steampunk Spotter](https://steampunk.si/spotter/) - an Assisted Automation Writing tool that analyzes and offers recommendations for your Ansible Playbooks. The tool has been developed by [XLAB Steampunk](https://steampunk.si/).
=> Add Steampunk Spotter from XLAB Steampunk

README.md
add Puzzle ITC Workshop for advanced Ansible users and beginners alike. Contains also tutorials about ansible-navigator and ansible-builder
=> Puzzle ansible workshop

README.md
Add a french blog which contains many posts on Ansible
=> Add french blog 

README.md
This PR updates some links to their new destination.
=> update: links for tower and packer provisioner

README.md
with antsichaut you can automate part of the release-process of a collection by automatically creating a changelog.yml file that gets the changes from pull requests
=> add antsichaut tool

README.md
=> feat: add book in list

README.md
link is to the repo with presentation, video recording and slides.
=> add link to SOLID-Ansible

README.md
Hey all,
I've added Ansible Template Playground, an online playground for running, testing and sharing Ansible templates.
=> Add Ansible Template Playground to tools
